#!/usr/local/bin/bash

up_file=$(mktemp)
otp_file=$(mktemp)
openvpn="$(brew --prefix openvpn)/sbin/openvpn"

if [[ ! $(op get item "$1") ]]; then
  eval "$(op signin)"
fi;
user=$(op get item "$1" | jq -r ".details.fields[0].value")

echo "$user" > "$up_file"
op get item "$1" | jq -r ".details.fields[1].value" >> "$up_file"

get_session_id=$(sudo "$openvpn" --config ~/.config/vpn/tips-lab.conf --auth-user-pass "$up_file" | grep AUTH_FAILED)

session_id=$(echo "$get_session_id" | cut -d':' -f7)
otp=$(op get totp "$1")

echo "$user" > "$otp_file"
echo "CRV1::$session_id::$otp" >> "$otp_file"

while read -r line; do
  [ -z "${line##*Initialization Sequence Completed*}" ] && break;
done < <(sudo "$openvpn" \
          --config ~/.config/vpn/tips-lab.conf \
          --auth-user-pass "$otp_file")

rm -rf "$up_file"
rm -rf "$otp_file"
echo

# sudo pkill -f "sudo $(brew --prefix openvpn)"
